#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install -y nginx
echo 'Holberton School' | tee /var/www/html/index.nginx-debian.html 
redict="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "19i $redict" /etc/nginx/sites-available/default
service nginx start
