#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install -y nginx
echo 'Holberton School' | tee /var/www/html/index.nginx-debian.html 
redict="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "19i $redict" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/error.html
error="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
sed -i "/server_name _;/a $error" /etc/nginx/sites-enabled/default
service nginx restart
