#!/usr/bin/env bash
# Installing nginx in a different server
sudo apt-get update -y
sudo apt-get install -y nginx
header="add_header X-Served-By $HOSTNAME;"
sudo sed -i "21i$header" /etc/nginx/sites-available/default
sudo service nginx restart
