#!/usr/bin/env bash
# Installing nginx in a different server
sudo apt-get -y update
sudo apt-get install -y nginx
header="add_header X-Served-By $HOSTNAME;"
sudo sed -i "20i $header" /etc/nginx/sites-available/default
sudo service nginx restart
