#!/usr/bin/env bash
# install and configures HAproxy
sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*

echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server webserver1 35.237.78.35:80 check
        server webserver2 35.237.247.197:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
