#!/usr/bin/env bash
# Install and configures HAproxy
sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*

  sudo echo "frontend http
        bind *:80
        mode http
        default_backend web-backend

        backend web-backend
        balance roundrobin
        server webserver1 35.237.247.197:80 check
        server webserver2 35.196.101.171:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
