#!/usr/bin/env bash
# Pings an IP address passed as an argument
# echo "$#"- argument
if [$# -lt 1]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    argument_ip=$1
    ping -c 5 "$argument_ip"
fi
