#!/usr/bin/env bash
# Web debugging-  Nginx is running as the nginx user.
sudo chown nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
